repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0  # Замените на актуальную версию
    hooks:
      - id: black
        language_version: python3.11  # Замените на версию Python, которую вы используете
