---
default_stages: [commit]
minimum_pre_commit_version: 3.0.0
default_language_version:
  python: python3.11
repos:
  - repo: local
    hooks:
      - id: front-lint
        name: front-lint
        files: ^frontend/
        entry: "yarn --cwd=frontend run lint-staged"
        pass_filenames: false
        language: system
      - id: front-translations-generate
        name: front-translations-generate
        files: ^frontend/
        entry: "yarn --cwd=frontend run translations:generate --silent"
        pass_filenames: false
        language: system
      - id: pipenv-lock-verify
        name: pipenv-lock-verify
        files: backend/(Pipfile|Pipfile.lock)
        entry: bash -c "cd backend && pipenv verify"
        pass_filenames: false
        language: system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements
        files: ^backend/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        files: ^backend/
        exclude: .*/(migrations)/.*
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        files: ^backend/

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        types_or: [python, ts, tsx, markdown]
        args: [--ignore-words, .codespell-ignore-words]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: "^backend/"
        exclude: |
          (?x)(
             .*/(migrations)/.*
             | backend/optimizer
             | backend/web_app
             | backend/computing
             | backend/custom_imports
           )
        args:
          - --no-strict-optional
          - --ignore-missing-imports
          - --config-file=backend/mypy.ini
        additional_dependencies:
          - types-PyYAML
          - types-python-dateutil
          - types-pytz
          - types-freezegun
          - types-requests
          - typing-extensions

      - id: mypy
        alias: mypy_pandas_stubs
        name: mypy_pandas_stubs
        files: |
          (?x)(
             backend/manage.py
             | backend/optimizer
             | backend/web_app
             | backend/computing
             | backend/custom_imports
           )
        exclude: ".*/(migrations)/.*"
        args:
          - --config-file=backend/mypy-pandas.ini
        additional_dependencies:
          - types-PyYAML
          - types-python-dateutil
          - types-pytz
          - types-freezegun
          - types-requests
          - typing-extensions
          - pandas-stubs==1.5.3.230214
          - pandas==1.5.*
          - numpy==1.24.*

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: |
          (?x)(
             .*/(migrations)/.*
             | frontend
             | infra/ansible
           )
        types_or: [html, json, yaml, toml, markdown, javascript]
        additional_dependencies:
          - prettier@2.2.0
          - prettier-plugin-toml@0.3.1

  # - repo: https://github.com/seddonym/import-linter
  #   rev: v1.2.7
  #   hooks:
  #     - id: import-linter
  #       files: ^backend/
  #       args:
  #         - --config=backend/.importlinter

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint
        exclude: Dockerfile.j2
        args:
          - --ignore
          - DL3008 # Pin versions in apt
          - --ignore
          - DL3018 # Pin versions in apk
          - --ignore
          - DL3013 # Pin versions in pip
          - --ignore
          - DL3025 # JSON notation CMD and ENTRYPOINT

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.91.0
    hooks:
      - id: terraform_fmt
        files: ^infra/

      - id: terragrunt_fmt
        files: ^infra/

      - id: terraform_tflint
        args:
          - --args=--enable-rule=terraform_documented_variables
        files: ^infra/
        exclude: ^infra/baby_yoda/tfvars/fwd

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
        args: ["-l", "-i", "4", "-ci", "-sr", "-w"]
      - id: shellcheck

  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.6
    hooks:
      - id: tfsec
        alias: tfsec-qantev-ad
        name: tfsec-qantev-ad
        files: ^infra/active_directory
        entry: tfsec infra/active_directory

      - id: tfsec
        alias: tfsec-clients
        name: tfsec-clients
        files: ^infra/clients
        entry: tfsec infra/clients

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.6.0
    hooks:
      - id: ansible-lint
        name: ansible-lint-babyyoda
        alias: ansible-lint-babyyoda
        entry: bash -c "cd infra/baby_yoda/ansible && python3 -m ansiblelint --force-color --fix"
        always_run: false
        files: ^infra/baby_yoda/ansible/
        exclude: ^molecule/
        additional_dependencies:
          - ansible

      - id: ansible-lint
        name: ansible-lint-role-tljh
        alias: ansible-lint-role-tljh
        entry: bash -c "cd infra/ansible/roles/ansible-role-tljh && python3 -m ansiblelint --force-color --fix"
        always_run: false
        files: ^infra/ansible/roles/ansible-role-tljh
        exclude: ^molecule/
        additional_dependencies:
          - ansible

      - id: ansible-lint
        name: ansible-fail2ban-role
        alias: ansible-fail2ban-role
        entry: bash -c "cd infra/ansible/roles/ansible_role_fail2ban && python3 -m ansiblelint --force-color --fix"
        always_run: false
        files: ^infra/ansible/roles/ansible_role_fail2ban
        exclude: ^molecule/
        additional_dependencies:
          - ansible

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.3
    hooks:
      - id: gitleaks
        args:
          - -c=.gitleaks.toml
