programs:
  ping_google:
    cmd: "ping google.com -c 5"
    numprocs: 1
    autostart: true
    autorestart: "unexpected"
    exitcodes: [0]
    startretries: 2
    stopsignal: "TERM"
    stoptime: 10
    stdout: "result/ping_google_out.log"
    stderr: "result/ping_google_err.log"
    workingdir: "/tmp"
    umask: "000"

  ls_home:
    cmd: "ls -la /home"
    numprocs: 1
    autostart: false
    autorestart: "always"
    exitcodes: [0]
    startretries: 2
    stopsignal: "TERM"
    stoptime: 5
    stdout: "result/ls_home_out.log"
    stderr: "result/ls_home_err.log"
    workingdir: "/home"
    umask: "022"

  curl_example:
    cmd: "curl example.com"
    numprocs: 1
    autostart: true
    autorestart: "never"
    exitcodes: [0]
    startretries: 1
    stopsignal: "TERM"
    stoptime: 5
    stdout: "result/curl_example_out.log"
    stderr: "result/curl_example_err.log"
    workingdir: "/tmp"
    umask: "022"