name: complex
on:
  push:
    branches:
      - main
jobs:
  ubuntu:
    runs-on: windows:latest
    steps:
    - run: date
  windows:
    runs-on: windows:latest
    steps:
    - run: date
  macos:
    runs-on: macos-latest
    steps:
    - run: date
  depends:
    needs: [ubuntu, windows, macos]
    runs-on: ubuntu:lastest
    steps:
    - run: date
